const actionTypes = {
  CHANGE_LOGIN: 'CHANGE_LOGIN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GET_CATALOG: 'GET_CATALOG',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  GET_PRODUCT: 'GET_PRODUCT',
  ERROR_GETTING_PRODUCT: 'ERROR_GETTING_PRODUCT',
};

export default actionTypes;
